In [7]:
import time, cv2
import os
from os import listdir
from os.path import isfile, join
import numpy as np
from scipy import ndimage


def read_folder(pth, label):
    pics = [f for f in listdir(pth) if isfile(join(pth, f))]
    imgs =[]
    for f in pics:
        img = cv2.imread(join(pth, f))
#         img = ndimage.imread(join(pth, f))
        imgs.append(img)
    labels = np.array([ label for ii in range(len(pics))])
    labels = (np.arange(4) == labels[:,None]).astype(np.float32)
    return imgs, labels
    
tmp_pics, tmp_labels = read_folder("/notebooks/car/CARCARCAR/ff", 0)
train_pics = tmp_pics[:33];  
train_labels = tmp_labels[:33]

tmp_pics, tmp_labels = read_folder("/notebooks/car/CARCARCAR/bb", 1)
train_pics = train_pics + tmp_pics[:33];  
train_labels = list(train_labels) + list(tmp_labels[:33])

tmp_pics, tmp_labels = read_folder("/notebooks/car/CARCARCAR/ll", 2)
train_pics = train_pics + tmp_pics[:33];  
train_labels = list(train_labels) + list(tmp_labels[:33])

tmp_pics, tmp_labels = read_folder("/notebooks/car/CARCARCAR/rr", 3)
train_pics = train_pics + tmp_pics[:33];  
train_labels = list(train_labels) + list(tmp_labels[:33])

train_pics = np.array(train_pics);  train_labels = np.array(train_labels)

print train_pics.shape, train_labels.shape


(132, 480, 640, 3) (132, 4)


In [8]:







import time, cv2
import os
from os import listdir
from os.path import isfile, join
import numpy as np
from scipy import ndimage


def read_folder(pth, label):
    pics = [f for f in listdir(pth) if isfile(join(pth, f))]
    imgs =[]
    for f in pics:
        img = cv2.imread(join(pth, f))
#         img = ndimage.imread(join(pth, f))
        imgs.append(img)
    labels = np.array([ label for ii in range(len(pics))])
    labels = (np.arange(4) == labels[:,None]).astype(np.float32)
    return imgs, labels
    
tmp_pics, tmp_labels = read_folder("/notebooks/car/obstacles/fff", 0)
train_pics = tmp_pics[-45:];  
train_labels = tmp_labels[-45:]

tmp_pics, tmp_labels = read_folder("/notebooks/car/obstacles/bbb", 1)
train_pics = train_pics + tmp_pics[:];  
train_labels = list(train_labels) + list(tmp_labels[:])

tmp_pics, tmp_labels = read_folder("/notebooks/car/obstacles/lll", 2)
train_pics = train_pics + tmp_pics[-45:];  
train_labels = list(train_labels) + list(tmp_labels[-45:])

tmp_pics, tmp_labels = read_folder("/notebooks/car/obstacles/rrr", 3)
train_pics = train_pics + tmp_pics[-45:];  
train_labels = list(train_labels) + list(tmp_labels[-45:])

train_pics = np.array(train_pics);  train_labels = np.array(train_labels)

print train_pics.shape, train_labels.shape




(180, 480, 640, 3) (180, 4)


In [9]:
# for ii in train_labels:
#     print ii

print train_pics[0]

[[[135 165 190]
  [135 165 190]
  [135 165 190]
  ..., 
  [ 85 106 134]
  [ 81 100 127]
  [ 85 104 131]]

 [[136 166 191]
  [136 166 191]
  [135 165 190]
  ..., 
  [ 84 105 133]
  [ 85 104 131]
  [ 85 104 131]]

 [[138 168 193]
  [137 167 192]
  [137 167 192]
  ..., 
  [ 80 101 129]
  [ 81 102 130]
  [ 75  96 124]]

 ..., 
 [[ 55  54  56]
  [ 57  59  60]
  [ 50  49  51]
  ..., 
  [ 57  61  72]
  [ 61  63  74]
  [ 61  63  74]]

 [[ 58  56  56]
  [ 39  39  39]
  [ 50  48  48]
  ..., 
  [ 86  88  99]
  [ 78  80  91]
  [ 78  80  91]]

 [[ 55  53  53]
  [ 61  59  59]
  [ 55  53  53]
  ..., 
  [ 79  81  92]
  [ 84  86  97]
  [ 88  90 101]]]


In [10]:
import cPickle as pickle
with open("read_data.pickle", "w") as f:
    pickle.dump({"pics": train_pics, "labels": train_labels}, f, pickle.HIGHEST_PROTOCOL)
print "done"

done
